### ISSUE TITLE
这个为什么是这样啊

### ISSUE THREAD

**Issue by testping** [JiaJie-xu1/VerticalTabLib#1]
![image](https://user-images.githubusercontent.com/28912967/109588359-918e9d00-7b43-11eb-9bd7-bab81cdb53d9.png)

**Comment by JiaJie-xu1** [comment]
你好，如果您的项目为非Androidx项目，您可以将依赖替换为这个‘q.rorbin:VerticalTabLayout:1.2.5’，参考这个项目的使用https://github.com/qstumn/VerticalTabLayout
